data:
  raw_path: data/raw/water_data_quality.csv
  train_processed_path: data/processed/processed_data_train.csv
  test_processed_path: data/processed/processed_data_test.csv
  invalid_records_path: data/invalid/  

  required_columns:
    - ph
    - turbidity
    - tds
    - status

  feature_columns:
    - ph_distance
    - tds_distance
    - turbidity_distance

    - ph_tds_ratio
    - turbidity_ph_ratio
    - tds_turbidity_ratio

    - ph_raw
    - tds_raw
    - turbidity_raw

    - ph_noise_score
    - tds_noise_score
    - turbidity_noise_score
    - instability_score

  label_column: status

  validation:
    ph:
      min: 0
      max: 14
    turbidity:
      min: 0
      max: 10000
    tds:
      min: 0
      max: 100000
    status:
      allowed_values: [0, 1]
    timestamp:
      format: "%Y-%m-%d %H:%M:%S"
      required: true

  missing_value_strategy:
    ph: "mean"
    turbidity: "median"
    tds: "mean"
    status: "mode"

  test_size: 0.2
  random_state: 42

model:
  version: 1
  base_path: models/
  filename: random_forest.pkl

  type: "random_forest"
  params:
    n_estimators: 200
    max_depth: 15
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
    class_weight: "balanced"

  label_encoder_path: data/processed/label_encoder.pkl

metrics:
  confusion_matrix_path: metrics/confusion_matrix.json
  classification_report_path: metrics/classification_report.json

logging:
  preprocessing_log: logs/preprocessing.log
  training_log: logs/training.log
  evaluation_log: logs/evaluation.log
  prediction_log: logs/prediction.log
  validation_log: logs/validation.log
  level: INFO
